const usersAnswer = [
    {
        id: 1,
        registrationDate: 1678891010,
        surname:"Калинько",
        name: "Арсений",
        fathersName: "Евгеньевич",
        login: "Arseniy",
        role: "admin"
    },
    {
        id: 2,
        registrationDate: 1678977410,
        surname:"Шванев",
        name: "Арсений",
        fathersName: "Алексеевич",
        login: "doctor",
        role: "user"
    },
    {
        id: 3,
        registrationDate: 1679063810,
        surname:"Бауэр",
        name: "Рудольф",
        fathersName: "Евгеньевич",
        login: "rudenf",
        role: "user"
    },
]

const patientsAnswer = [
    {
        id: 8,
        dateOfAdmission: 1672954315,
        probabilityOfDeath: true,
        sex: true,
        age: 49,
        urea: 234,
        creatinine: 523,
        ast: 131,
        alt: 4121,
        glucose: 633,
        leukocytes: 5233,
        platelets: 890,
        neutrophils: 67,
        lymphocytes: 870,
        dDimer: 5654,
        ag:  false,
        sd: true,
        ibs: true,
        hobl: false,
        hbp: true,
        crp: 74,
        skf: 234,
        neutrophilLymphocyteRatio: 2345,
        cabsType: true,
        bmi: 235,
        overweight:  false,
        smoking: true,
        heredity:  false,
        dyslipidemia: true,
        hoblBa:  false,
        piks: true,
        fp:  false,
        su: true,
        th:  false,
        varicose: true,
        cardiacLesions:  false,
        llaLesions: true,
        fcAnginaPectoris:  false,
        fcchf: true,
        lvef: 2342,
        is: 134,
        euroScore2: 253, 
        ik: 235,
        ikTime: 524,
        aorticClampTime: 234,
        tBodies: 4234,
        numberOfCardioplegias:  false,
        vpLz: true,
        revascularizationIndex:  false,
        tTypeCobs: true,
        limaExcretion:  false,
        rimaExcretion: "s",
        laUsage:  false,
        avUsage: true,
        bloodLoss: 7454,
        alvTime: 2345,
        inotropicSupport: true,
        pneumonia:  false,
        sn: true,
        fpTp:  false,
        pleuralEffusion: true,
        hydropericardium:  false,
        pneumothorax: true,
        sternalComplications:  false,
        akk: true,
        iapf:  false,
        spironolactone: true,
        diuretics:  false,
        cordaron: true,
        hospitalizationDuration: 25,
        ceaFteer:  false,
        ancoPerationsAfter: true,
        antiplateletAgentsAfter:  false,
        anticoagulants: true,
        babAfter:  false,
        akkAfter: true,
        iAPFAfter:  false,
        araAfter: true,
        diureticsAfter:  false,
        statins: true,
        heartAttack:  false,
        PCI: true,
        insult:  false,
        death: true
        
    },
    {
        id: 2,
        dateOfAdmission: 1672955825,
        probabilityOfDeath: true,
        sex: true,
        age: 45,
        urea: 234,
        creatinine: 523,
        ast: 131,
        alt: 4121,
        glucose: 633,
        leukocytes: 5233,
        platelets: 890,
        neutrophils: 67,
        lymphocytes: 870,
        dDimer: 5654,
        ag:  false,
        sd: true,
        ibs: true,
        hobl: false,
        hbp: true,
        crp: 74,
        skf: 234,
        neutrophilLymphocyteRatio: 2345,
        cabsType: true,
        bmi: 235,
        overweight:  false,
        smoking: true,
        heredity:  false,
        dyslipidemia: true,
        hoblBa:  false,
        piks: true,
        fp:  false,
        su: true,
        th:  false,
        varicose: true,
        cardiacLesions:  false,
        llaLesions: true,
        fcAnginaPectoris:  false,
        fcchf: true,
        lvef: 2342,
        is: 134,
        euroScore2: 253, 
        ik: 235,
        ikTime: 524,
        aorticClampTime: 234,
        tBodies: 4234,
        numberOfCardioplegias:  false,
        vpLz: true,
        revascularizationIndex:  false,
        tTypeCobs: true,
        limaExcretion:  false,
        rimaExcretion: "f",
        laUsage:  false,
        avUsage: true,
        bloodLoss: 7454,
        alvTime: 2345,
        inotropicSupport: true,
        pneumonia:  false,
        sn: true,
        fpTp:  false,
        pleuralEffusion: true,
        hydropericardium:  false,
        pneumothorax: true,
        sternalComplications:  false,
        akk: true,
        iapf:  false,
        spironolactone: true,
        diuretics:  false,
        cordaron: true,
        hospitalizationDuration: 25,
        ceaFteer:  false,
        ancoPerationsAfter: true,
        antiplateletAgentsAfter:  false,
        anticoagulants: true,
        babAfter:  false,
        akkAfter: true,
        iAPFAfter:  false,
        araAfter: true,
        diureticsAfter:  false,
        statins: true,
        heartAttack:  false,
        PCI: true,
        insult:  false,
        death: true
    },
    {
        id: 12,
        dateOfAdmission: 1672954356,
        probabilityOfDeath: false,
        sex: false,
        age: 60,
        urea: 234,
        creatinine: 523,
        ast: 131,
        alt: 4121,
        glucose: 633,
        leukocytes: 5233,
        platelets: 890,
        neutrophils: 67,
        lymphocytes: 870,
        dDimer: 5654,
        ag:  false,
        sd: true,
        ibs: true,
        hobl: false,
        hbp: true,
        crp: 74,
        skf: 234,
        neutrophilLymphocyteRatio: 2345,
        cabsType: true,
        bmi: 235,
        overweight:  false,
        smoking: true,
        heredity:  false,
        dyslipidemia: true,
        hoblBa:  false,
        piks: true,
        fp:  false,
        su: true,
        th:  false,
        varicose: true,
        cardiacLesions:  false,
        llaLesions: true,
        fcAnginaPectoris:  false,
        fcchf: true,
        lvef: 2342,
        is: 134,
        euroScore2: 253, 
        ik: 235,
        ikTime: 524,
        aorticClampTime: 234,
        tBodies: 4234,
        numberOfCardioplegias:  false,
        vpLz: true,
        revascularizationIndex:  false,
        tTypeCobs: true,
        limaExcretion:  false,
        rimaExcretion: "n",
        laUsage:  false,
        avUsage: true,
        bloodLoss: 7454,
        alvTime: 2345,
        inotropicSupport: true,
        pneumonia:  false,
        sn: true,
        fpTp:  false,
        pleuralEffusion: true,
        hydropericardium:  false,
        pneumothorax: true,
        sternalComplications:  false,
        akk: true,
        iapf:  false,
        spironolactone: true,
        diuretics:  false,
        cordaron: true,
        hospitalizationDuration: 25,
        ceaFteer:  false,
        ancoPerationsAfter: true,
        antiplateletAgentsAfter:  false,
        anticoagulants: true,
        babAfter:  false,
        akkAfter: true,
        iAPFAfter:  false,
        araAfter: true,
        diureticsAfter:  false,
        statins: true,
        heartAttack:  false,
        PCI: true,
        insult:  false,
        death: false
    }
]

const cabsParametersAnswer = [

]

const covidParametersAnswer = [
    {
      "label": "Пол",
      "name": "sex",
      "type": "doubleSelection",
      "values": ["Муж", "Жен"],
      "isRequired": true
    },
    {
      "label": "Возраст",
      "name": "age",
      "type": "textInput",
      "isRequired": true,
      "inputLimitation": 120.0
    },
    {
      "label": "Мочевина",
      "name": "urea",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 250.0
    },
    {
      "label": "Креатинин",
      "name": "creatinine",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 5.0
    },
    {
      "label": "АСТ",
      "name": "ast",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 200.0
    },
    {
      "label": "АЛТ",
      "name": "alt",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 200.0
    },
    {
      "label": "Глюкоза",
      "name": "glucose",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 300.0
    },
    {
      "label": "Лейкоциты",
      "name": "leukocytes",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 30.0
    },
    {
      "label": "Тромбоциты",
      "name": "platelets",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 800.0
    },
    {
      "label": "Нейтрофилы",
      "name": "neutrophils",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 15.0
    },
    {
      "label": "Лимфоциты",
      "name": "lymphocytes",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 10.0
    },
    {
      "label": "D-димер",
      "name": "dDimer",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 5.0
    },
    {
      "label": "АГ",
      "name": "ag",
      "type": "doubleSelection",
      "values": ["Да", "Нет"],
      "isRequired": false,
    },
    {
      "label": "СД",
      "name": "sd",
      "type": "doubleSelection",
      "values": ["Да", "Нет"],
      "isRequired": false,
    },
    {
      "label": "ИБС (с ХСН)",
      "name": "ibs",
      "type": "doubleSelection",
      "values": ["Да", "Нет"],
      "isRequired": false,
    },
    {
      "label": "ХОБЛ + астма",
      "name": "hobl",
      "type": "doubleSelection",
      "values": ["Да", "Нет"],
      "isRequired": false,
    },
    {
      "label": "ХБП (3-5)",
      "name": "hbp",
      "type": "doubleSelection",
      "values": ["Да", "Нет"],
      "isRequired": false,
    },
    {
      "label": "CRP",
      "name": "crp",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 300.0
    },
    {
      "label": "СКФ (CKD-EPI 2021)",
      "name": "skf",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 100.0
    },
    {
      "label": "Нейтрофил-лимф. соотношение",
      "name": "neutrophilLymphocyteRatio",
      "type": "textInput",
      "isRequired": false,
      "inputLimitation": 30.0
    }
  ]

export {usersAnswer, patientsAnswer, cabsParametersAnswer, covidParametersAnswer }