import Token from "./Token";

import Request from "../Request"

import Patient from './Patient'

class Patients {

    constructor(){
        this.answer = true;
        this.patients = []
    }

    async getPatients(accessToken, refreshToken){

        let patientsAnswer = [
            {
                id: 8,
                dateOfAdmission: 1672954315,
                probabilityOfDeath: 10,
                sex: true,
                age: 45,
                urea: 234,
                creatinine: 523,
                ast: 131,
                alt: 4121,
                glucose: 633,
                leukocytes: 5233,
                platelets: 890,
                neutrophils: 67,
                lymphocytes: 870,
                dDimer: 5654,
                ag:  false,
                sd: true,
                ibs: true,
                hobl: false,
                hbp: true,
                crp: 74,
                skf: 234,
                neutrophilLymphocyteRatio: 2345,
                cabsType: true,
                bmi: 235,
                overweight:  false,
                smoking: true,
                heredity:  false,
                dyslipidemia: true,
                hoblBa:  false,
                piks: true,
                fp:  false,
                su: true,
                th:  false,
                varicose: true,
                cardiacLesions:  false,
                llaLesions: true,
                fcAnginaPectoris:  false,
                fcchf: true,
                lvef: 2342,
                is: 134,
                euroScore2: 253, 
                ik: 235,
                ikTime: 524,
                aorticClampTime: 234,
                tBodies: 4234,
                numberOfCardioplegias:  false,
                vpLz: true,
                revascularizationIndex:  false,
                tTypeCobs: true,
                limaExcretion:  false,
                rimaExcretion: true,
                laUsage:  false,
                avUsage: true,
                bloodLoss: 7454,
                alvTime: 2345,
                inotropicSupport: true,
                pneumonia:  false,
                sn: true,
                fpTp:  false,
                pleuralEffusion: true,
                hydropericardium:  false,
                pneumothorax: true,
                sternalComplications:  false,
                akk: true,
                iapf:  false,
                spironolactone: true,
                diuretics:  false,
                cordaron: true,
                hospitalizationDuration: 25,
                ceaFteer:  false,
                ancoPerationsAfter: true,
                antiplateletAgentsAfter:  false,
                anticoagulants: true,
                babAfter:  false,
                akkAfter: true,
                iAPFAfter:  false,
                araAfter: true,
                diureticsAfter:  false,
                statins: true,
                heartAttack:  false,
                PCI: true,
                insult:  false,
                death: true
                
            },
            {
                id: 2,
                dateOfAdmission: 1672955825,
                probabilityOfDeath: 25,
                sex: true,
                age: 45,
                urea: 234,
                creatinine: 523,
                ast: 131,
                alt: 4121,
                glucose: 633,
                leukocytes: 5233,
                platelets: 890,
                neutrophils: 67,
                lymphocytes: 870,
                dDimer: 5654,
                ag:  false,
                sd: true,
                ibs: true,
                hobl: false,
                hbp: true,
                crp: 74,
                skf: 234,
                neutrophilLymphocyteRatio: 2345,
                cabsType: true,
                bmi: 235,
                overweight:  false,
                smoking: true,
                heredity:  false,
                dyslipidemia: true,
                hoblBa:  false,
                piks: true,
                fp:  false,
                su: true,
                th:  false,
                varicose: true,
                cardiacLesions:  false,
                llaLesions: true,
                fcAnginaPectoris:  false,
                fcchf: true,
                lvef: 2342,
                is: 134,
                euroScore2: 253, 
                ik: 235,
                ikTime: 524,
                aorticClampTime: 234,
                tBodies: 4234,
                numberOfCardioplegias:  false,
                vpLz: true,
                revascularizationIndex:  false,
                tTypeCobs: true,
                limaExcretion:  false,
                rimaExcretion: true,
                laUsage:  false,
                avUsage: true,
                bloodLoss: 7454,
                alvTime: 2345,
                inotropicSupport: true,
                pneumonia:  false,
                sn: true,
                fpTp:  false,
                pleuralEffusion: true,
                hydropericardium:  false,
                pneumothorax: true,
                sternalComplications:  false,
                akk: true,
                iapf:  false,
                spironolactone: true,
                diuretics:  false,
                cordaron: true,
                hospitalizationDuration: 25,
                ceaFteer:  false,
                ancoPerationsAfter: true,
                antiplateletAgentsAfter:  false,
                anticoagulants: true,
                babAfter:  false,
                akkAfter: true,
                iAPFAfter:  false,
                araAfter: true,
                diureticsAfter:  false,
                statins: true,
                heartAttack:  false,
                PCI: true,
                insult:  false,
                death: true
            },
            {
                id: 12,
                dateOfAdmission: 1672954356,
                probabilityOfDeath: 30,
                sex: false,
                age: 45,
                urea: 234,
                creatinine: 523,
                ast: 131,
                alt: 4121,
                glucose: 633,
                leukocytes: 5233,
                platelets: 890,
                neutrophils: 67,
                lymphocytes: 870,
                dDimer: 5654,
                ag:  false,
                sd: true,
                ibs: true,
                hobl: false,
                hbp: true,
                crp: 74,
                skf: 234,
                neutrophilLymphocyteRatio: 2345,
                cabsType: true,
                bmi: 235,
                overweight:  false,
                smoking: true,
                heredity:  false,
                dyslipidemia: true,
                hoblBa:  false,
                piks: true,
                fp:  false,
                su: true,
                th:  false,
                varicose: true,
                cardiacLesions:  false,
                llaLesions: true,
                fcAnginaPectoris:  false,
                fcchf: true,
                lvef: 2342,
                is: 134,
                euroScore2: 253, 
                ik: 235,
                ikTime: 524,
                aorticClampTime: 234,
                tBodies: 4234,
                numberOfCardioplegias:  false,
                vpLz: true,
                revascularizationIndex:  false,
                tTypeCobs: true,
                limaExcretion:  false,
                rimaExcretion: true,
                laUsage:  false,
                avUsage: true,
                bloodLoss: 7454,
                alvTime: 2345,
                inotropicSupport: true,
                pneumonia:  false,
                sn: true,
                fpTp:  false,
                pleuralEffusion: true,
                hydropericardium:  false,
                pneumothorax: true,
                sternalComplications:  false,
                akk: true,
                iapf:  false,
                spironolactone: true,
                diuretics:  false,
                cordaron: true,
                hospitalizationDuration: 25,
                ceaFteer:  false,
                ancoPerationsAfter: true,
                antiplateletAgentsAfter:  false,
                anticoagulants: true,
                babAfter:  false,
                akkAfter: true,
                iAPFAfter:  false,
                araAfter: true,
                diureticsAfter:  false,
                statins: true,
                heartAttack:  false,
                PCI: true,
                insult:  false,
                death: true
            }
        ]

        for(let i = 0; i < patientsAnswer.length; i++){
            this.patients.push(new Patient(patientsAnswer[i].id, patientsAnswer[i].dateOfAdmission, patientsAnswer[i].probabilityOfDeath, 
        patientsAnswer[i].sex, patientsAnswer[i].age, patientsAnswer[i].urea, patientsAnswer[i].creatinine, patientsAnswer[i].ast, patientsAnswer[i].alt, patientsAnswer[i].glucose, patientsAnswer[i].leukocytes, 
        patientsAnswer[i].platelets, patientsAnswer[i].neutrophils, patientsAnswer[i].lymphocytes, patientsAnswer[i].dDimer, patientsAnswer[i].ag, patientsAnswer[i].sd, patientsAnswer[i].ibs, patientsAnswer[i].hobl, 
        patientsAnswer[i].hbp, patientsAnswer[i].crp, patientsAnswer[i].skf, patientsAnswer[i].neutrophilLymphocyteRatio, patientsAnswer[i].cabsType, patientsAnswer[i].bmi, patientsAnswer[i].overweight, 
        patientsAnswer[i].smoking, patientsAnswer[i].heredity, patientsAnswer[i].dyslipidemia, patientsAnswer[i].hoblBa, patientsAnswer[i].piks, patientsAnswer[i].fp, patientsAnswer[i].su, patientsAnswer[i].th, patientsAnswer[i].varicose, 
        patientsAnswer[i].cardiacLesions, patientsAnswer[i].llaLesions, patientsAnswer[i].fcAnginaPectoris, patientsAnswer[i].fcchf, patientsAnswer[i].lvef, patientsAnswer[i].is, patientsAnswer[i].euroScore2, 
        patientsAnswer[i].ik, patientsAnswer[i].ikTime, patientsAnswer[i].aorticClampTime, patientsAnswer[i].tBodies, patientsAnswer[i].numberOfCardioplegias, patientsAnswer[i].vpLz, 
        patientsAnswer[i].revascularizationIndex, patientsAnswer[i].tTypeCobs, patientsAnswer[i].limaExcretion, patientsAnswer[i].rimaExcretion, patientsAnswer[i].laUsage, 
        patientsAnswer[i].avUsage, patientsAnswer[i].bloodLoss, patientsAnswer[i].alvTime, patientsAnswer[i].inotropicSupport, patientsAnswer[i].pneumonia, patientsAnswer[i].sn, patientsAnswer[i].fpTp, 
        patientsAnswer[i].pleuralEffusion, patientsAnswer[i].hydropericardium, patientsAnswer[i].pneumothorax, patientsAnswer[i].sternalComplications, 
        patientsAnswer[i].akk, patientsAnswer[i].iapf, patientsAnswer[i].spironolactone, patientsAnswer[i].diuretics, patientsAnswer[i].cordaron, patientsAnswer[i].hospitalizationDuration, 
        patientsAnswer[i].ceaFteer, patientsAnswer[i].ancoPerationsAfter, patientsAnswer[i].antiplateletAgentsAfter, patientsAnswer[i].anticoagulants, 
        patientsAnswer[i].babAfter, patientsAnswer[i].akkAfter, patientsAnswer[i].iAPFAfter, patientsAnswer[i].araAfter, patientsAnswer[i].diureticsAfter, patientsAnswer[i].statins, 
        patientsAnswer[i].heartAttack, patientsAnswer[i].PCI, patientsAnswer[i].insult, patientsAnswer[i].death))
        }
    }

}

export default Patients
