/**
 * Cardio-in-the-VaiN
 * The API for the Cardio Center project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthorizationScheme model module.
 * @module model/AuthorizationScheme
 * @version 1.0
 */
class AuthorizationScheme {
    /**
     * Constructs a new <code>AuthorizationScheme</code>.
     * @alias module:model/AuthorizationScheme
     */
    constructor() { 
        
        AuthorizationScheme.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthorizationScheme</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthorizationScheme} obj Optional instance to populate.
     * @return {module:model/AuthorizationScheme} The populated <code>AuthorizationScheme</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorizationScheme();

            if (data.hasOwnProperty('accessToken')) {
                obj['accessToken'] = ApiClient.convertToType(data['accessToken'], 'String');
            }
            if (data.hasOwnProperty('refreshToken')) {
                obj['refreshToken'] = ApiClient.convertToType(data['refreshToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} accessToken
 */
AuthorizationScheme.prototype['accessToken'] = undefined;

/**
 * @member {String} refreshToken
 */
AuthorizationScheme.prototype['refreshToken'] = undefined;






export default AuthorizationScheme;

