/**
 * Cardio-in-the-VaiN
 * The API for the Cardio Center project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthCredentials model module.
 * @module model/AuthCredentials
 * @version 1.0
 */
class AuthCredentials {
    /**
     * Constructs a new <code>AuthCredentials</code>.
     * @alias module:model/AuthCredentials
     * @param username {String} 
     * @param password {String} 
     */
    constructor(username, password) { 
        
        AuthCredentials.initialize(this, username, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password) { 
        obj['username'] = username;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>AuthCredentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthCredentials} obj Optional instance to populate.
     * @return {module:model/AuthCredentials} The populated <code>AuthCredentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthCredentials();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
AuthCredentials.prototype['username'] = undefined;

/**
 * @member {String} password
 */
AuthCredentials.prototype['password'] = undefined;






export default AuthCredentials;

