/**
 * Cardio-in-the-VaiN
 * The API for the Cardio Center project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FormField from './FormField';

/**
 * The FormStep model module.
 * @module model/FormStep
 * @version 1.0
 */
class FormStep {
    /**
     * Constructs a new <code>FormStep</code>.
     * @alias module:model/FormStep
     */
    constructor() { 
        
        FormStep.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FormStep</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FormStep} obj Optional instance to populate.
     * @return {module:model/FormStep} The populated <code>FormStep</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FormStep();

            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [FormField]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} label
 */
FormStep.prototype['label'] = undefined;

/**
 * @member {Array.<module:model/FormField>} fields
 */
FormStep.prototype['fields'] = undefined;






export default FormStep;

