/**
 * Cardio-in-the-VaiN
 * The API for the Cardio Center project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The UsersPagination model module.
 * @module model/UsersPagination
 * @version 1.0
 */
class UsersPagination {
    /**
     * Constructs a new <code>UsersPagination</code>.
     * @alias module:model/UsersPagination
     */
    constructor() { 
        
        UsersPagination.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersPagination</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersPagination} obj Optional instance to populate.
     * @return {module:model/UsersPagination} The populated <code>UsersPagination</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersPagination();

            if (data.hasOwnProperty('contents')) {
                obj['contents'] = ApiClient.convertToType(data['contents'], [User]);
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
            if (data.hasOwnProperty('numberOfElements')) {
                obj['numberOfElements'] = ApiClient.convertToType(data['numberOfElements'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/User>} contents
 */
UsersPagination.prototype['contents'] = undefined;

/**
 * @member {Number} page
 */
UsersPagination.prototype['page'] = undefined;

/**
 * @member {Number} pageSize
 */
UsersPagination.prototype['pageSize'] = undefined;

/**
 * @member {Number} numberOfElements
 */
UsersPagination.prototype['numberOfElements'] = undefined;

/**
 * @member {Number} totalPages
 */
UsersPagination.prototype['totalPages'] = undefined;

/**
 * @member {Number} totalElements
 */
UsersPagination.prototype['totalElements'] = undefined;






export default UsersPagination;

