/**
 * Cardio-in-the-VaiN
 * The API for the Cardio Center project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FormStep from './FormStep';

/**
 * The WizardForm model module.
 * @module model/WizardForm
 * @version 1.0
 */
class WizardForm {
    /**
     * Constructs a new <code>WizardForm</code>.
     * @alias module:model/WizardForm
     */
    constructor() { 
        
        WizardForm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WizardForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WizardForm} obj Optional instance to populate.
     * @return {module:model/WizardForm} The populated <code>WizardForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WizardForm();

            if (data.hasOwnProperty('steps')) {
                obj['steps'] = ApiClient.convertToType(data['steps'], [FormStep]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/FormStep>} steps
 */
WizardForm.prototype['steps'] = undefined;






export default WizardForm;

